### ISSUE TITLE
install mapnik-sdk and run demo

### ISSUE THREAD

**Issue by hcfang2000** [mapbox/windows-builds#100]
I think I have had a successful build following the build procedures.  I get a full mapnik-sdk sub-directory and it looks like it's the build result.  

What's the right way to install it?  I could not find any documentation or instructions for the following steps.  I could not run the demo rundemo.py successfully either under the new build.

**Comment by BergWerkGIS** [comment]
> I could not run the demo rundemo.py successfully either under the new build.

It's not possible to run the Python bindings/demos as they are currently failing to build on Windows, see #92 

-----

Quick rundown for the C++ demo:

```
CD into mapnik SDK directory
set-env-vars.bat
cd demo\c++
git clone https://chromium.googlesource.com/external/gyp.git gyp
gyp\gyp.bat rundemo.gyp --depth=. -f msvs -G msvs_version=2015
rundemo.sln <- this opes VS
```

Add `x64` platform to the solution
Change the following paths in `rundemo.cpp`:
* `register_datasources` => `lib/mapnik/input/`
* `register_font` => `lib/mapnik/fonts/dejavu-fonts-ttf-2.37/ttf/DejaVuSans.ttf`

Build and exit VS.

```
cd back into the root directory of the mapnik SDK
demo\c++\Debug\rundemo.exe
```

You should now have some `demo.*` in the root directory of mapnik SDK.

**Comment by hcfang2000** [comment]
Your step-by-step instruction is really INVALUABLE.  It works.  Too happy!

This instructions should be put inside the README.md.  Thank you very very much.
