### ISSUE TITLE
Handling mapnik branches with /

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#23]
@BergWerkGIS - @flippmoke has a Mapnik branch named `release/image_data_any` and I noticed that this breaks our `build_mapnik.bat` script because the `/` leads to an unexpected nested directory.

This branch will soon be merged into Mapnik master so I don't think we need to make any changes to support this, but I wanted to give you a heads up nonetheless in case this helps save you debugging time if you ever set out to build another branch with this kind of naming.

**Comment by BergWerkGIS** [comment]
Had a look, but couldn't make it work.
Will have another look when there will be strange naming again in the future.

**Comment by springmeyer** [comment]
Yes, no need for action on this now (we're merged and the branch is gone).
