### ISSUE TITLE
Port scripts to powershell

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#24]
The scripts are batch because:

 - @springmeyer wanted to keep it simple and similar to mapnik-packaging (in that batch is fairly similiar to bash)
 - @springmeyer always struggles to install powershell and understand its permissions - it seems like it behaves differently on different machines

But those are both lousy reasons for sticking with batch, and now that @BergWerkGIS - who is experienced with powershell - is pushing hard on these scripts, let's switch to powershell where appropriate.

TODO:

  - [ ] Document clearly in the readme how to set up powershell and document any gochas and noob details for now to run scripts
  - [ ] Close this ticket and create new tickets for any scripts that should be ported (if discussion is needed) otherwise JFDI.

**Comment by BergWerkGIS** [comment]
As discussed on chat, I will tackle this as time permits or on the fly when necessary.
I don't think there is a urgent need to do it right away.

P.S.: WRT PowerShell: With current OS (8.1, 2012) there shouldn't be anything more to do than just call it `powershell <cmd>`.
Maybe `powershell Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted -Force`

**Comment by springmeyer** [comment]
> Maybe powershell Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted -Force

Okay, can you add instruction to the readme and then close this out?

**Comment by BergWerkGIS** [comment]
No need to document, I just do it automatically, [like so](https://github.com/mapnik/mapnik-gyp/blob/01f0b3d14296c272a0d262d21a10d75a9f6c9351/build.bat#L422)

The last real need for a BAT file :smirk:

**Comment by springmeyer** [comment]
oh, so you are saying that that line is needed everytime before running a powershell script? And therefore wrapping powershell in bat is the best approach? I see this also at https://github.com/mapbox/windows-builds/blob/master/linktype.bat#L12.

**Comment by BergWerkGIS** [comment]
You got me :smirk: . No, it's not necessary every time. Both occurrences are just quick hacks.
Will do it properly in settings.bat: check policy and adjust only if necessary, and do a proper bail out, if user is not allowed to change policy.

**Comment by BergWerkGIS** [comment]
Not going to go he Powershell route.

Decided to go with `ScriptCs`:
[scripts/build.csx](https://github.com/mapbox/windows-builds/blob/f0b8bac92db02a0cafb28d8faba6a23202f9fdbc/scripts/build.csx)
[wip] for mapink: https://github.com/mapnik/mapnik-gyp/compare/new-win-build-scripts
