### ISSUE TITLE
Add publish process

### ISSUE THREAD

**Issue by bsudekum** [mapbox/windows-builds#26]
@BergWerkGIS I started to scope out the publishing process on /build, see initial commit here: https://github.com/mapbox/windows-builds/commit/923f34c7d33f0fb6baebfa590b3428b0a46e1608

Basically, travis spins up, and runs [`publish-binary.sh`](https://github.com/mapbox/windows-builds/commit/923f34c7d33f0fb6baebfa590b3428b0a46e1608#diff-354f30a63fb0907d4ad57269548329e3R15). In publish binary, 

1. Instance is created
2. Userdata script is added
 * here, http://www.bergwerk-gis.at/dl/mapbox/build.txt runs
 * then the binary should be uploaded to s3
 * finally, the instance should shut it self down. This can happen inside the userdata script as the last step
3. Meanwhile, we wait until the instance is shutdown
4. once shutdown, terminate the instance
5. if however the instance does not shutdown after x seconds, terminate due to failure and report an `exit 0`

Let me know how this all sounds to you.

**Comment by BergWerkGIS** [comment]
@bsudekum Thanks. I'll take a look at it during the weekend.
We have planned to to put it into the mapnik repo.

**Comment by BergWerkGIS** [comment]
Automatic build chain works!
