### ISSUE TITLE
Changes for VS2015 CTP6

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/windows-builds#28]
CTP 6 seem to contain some bigger changes.
Opening a comment for each problem in this thread.

* [boost](https://github.com/mapbox/windows-builds/issues/28#issuecomment-76071267)
* [OS](https://github.com/mapbox/windows-builds/issues/28#issuecomment-76515677)

**Comment by BergWerkGIS** [comment]
# Boost

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\crtdefs.h(10):
fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory
```

CTP6 seems to have changed paths for the WinSDK from `8.1` to `10`.

Previously: `...\Windows Kits\8.1`

Now:
![image](https://cloud.githubusercontent.com/assets/4549888/6381638/0e68dcc0-bd43-11e4-85d7-8fb9be6d9ce4.png)

**Comment by BergWerkGIS** [comment]
# Operating System itself

It seems that CTP6 changes the operating system in undocumented ways that make it impossible to run Mapbox Studio.
As of today (Sat, Feb 28) no mentions about anything interesting for us, either under `Known issues` or `Breaking changes`:
http://support.microsoft.com/kb/2967191

I've verified with Windows 8.1 and Windows Server 2012 R2

### Windows 8.1

My main local dev machine is seriously screwed now.
After the upgrade from `CTP5` to `CTP6` I wasn't able to compile `boost` (see above).
Mapbox studio failed with `Unable to create pipe "\\.\pipe\chrome`:
https://github.com/mapbox/mapbox-studio/issues/1190
https://github.com/mapbox/mapbox-studio-internal/issues/200

* Manually running setup of `vcredist CTP4` (the current version Studio is built with) again, didn't change anything
* Uninstalling CTP6 didn't change anything
* Installing CTP5 again didn't change anything
  * __except that now I cannot build anything__: as VS's  own `cl.exe` fails with our very first dependency `zlib`

![image](https://cloud.githubusercontent.com/assets/4549888/6425319/3e3e6cc0-bf24-11e4-9a55-e77a2f017f1e.png)


### Windows Server 2012 R2

* booted a vanilla 2012 R2 instance
* installed Studio 0.2.5
* Studio ran successfully
* Installed CTP6
* Studio didn't start anymore: ``Unable to create pipe "\\.\pipe\chrome`
* Tried to build Studio with CTP6
  * at the moment I'm stuck at `node-mapnik` as `npm install` downloads `node.lib` from S3, even when pointing to the locally built node.
  * I'll keep looking where to override that

**Comment by BergWerkGIS** [comment]
Unistalling CTP6 and additionally removing everything manually, that was installed by CTP6, but not removed by the uninstaller, doesn't solve anything.

After a reinstall of CTP5:
* `zlib` compiles via commandline, but `zlib.vcxproj` cannot even be opened from within VS.
* `boost` even fails to compile via commandline.

**Comment by BergWerkGIS** [comment]
Update on my quest "Restore W8.1 after VS2015 CTP6"

* Uninstalled 20**15** CTP __5__
* manually removed everything that was additionally installed but not removed
* installed 20**14** CTP __4__
* 2014 CTP 4 just appears for a flash and is gone
* deleted (to no avail):
  * HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0
  * HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0_Config
  * %USERPROFILE%\AppData\Roaming\Microsoft\VisualStudio
* tried (to no avail):
  * cd "c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE"
  * devenv.exe /safemode
  * devenv.exe /resetskippkgs
  * devenv.exe /installvstemplates
  * devenv.exe /resetsettings
  * devenv.exe /resetuserdata

**Comment by springmeyer** [comment]
wow. I had no idea the potential problems from CTP. does Microsoft have any kind of bug tracker where this can be reported?

**Comment by BergWerkGIS** [comment]
y, they do, but answers to CTP questions/bug reports are most of the time like this:
`Thanks for reporting. It is already on our list. As you know: this is CTP, don't use in production.`

I wanted to avoid reinstalling ,Windows, but I've already spent way too much time with this.
I think, first thing on Monday is a new setup of the MacBook.

And as mentioned above: boost doesn't even compile on a fresh machine with just CTP6 installed.

I suggest we stay with 2014 CTP 4 for now.

**Comment by BergWerkGIS** [comment]
Ok, I'm up and running again with a fresh install of W8.1, VS2014 CTP4 and everything else.

Closing this issuse.
We will stay with VS20**14** CTP**4** for now, till a more reliable VS20**15** CTP**7** or **RTM** comes out.

I couldn't get `boost` to compile with 2015 CTP6 on a fresh machine with just VS on it, anyway.

@springmeyer @flippmoke 
I know a lot of things a moving at the moment (coverage), but just wanted to let you know, I get this error with latest master:

![image](https://cloud.githubusercontent.com/assets/4549888/6673509/fe698fce-cc13-11e4-8a84-1408808fa8aa.png)

**Comment by cdglove** [comment]
This may help you.  I ran into the same issue on another project, and the culprit turned out to be that some boost build generated bat files were not being regenerated with the updated CRT include paths.  They will reside in your temp directory and have names like b2_msvc_14.0_vcvarsall_amd64.cmd.  Manually removing the files corrected the problem for me. I can now build boost on CTP6.

**Comment by BergWerkGIS** [comment]
@cdglove 
Great info, but I couldn't find the referenced file `b2_msvc_14.0_vcvarsall_amd64.cmd` or anything similar on my system.

However, I removed all already extracted sources and all other tmp files I could find, started completely from scratch and **now the build magically started working**, including everything up to *mapnik*. I've not yet tried *node-mapnik*.

Thanks for sharing and making me look into it again.

Out of curiosity: Did you have any other problems when updating VS?
As you might have read updating to CTP6 totally destroyed my dev machine.
My route was CTP2, CTP4, CTP5, CTP6 (and the 2015 Preview somewhere in between).

/cc @springmeyer

**Comment by jpvanoosten** [comment]
@cdglove Good call! This fixed it for me too. I built the boots libraries initially with CTP5 and tried to rebuild with CTP6 and got the same error. Deleting those .cmd files in the Temp folder fixed it for me.

**Comment by sergey-shandar** [comment]
@cdglove Excellent call to clean up temp folder! Thank you.

**Comment by BergWerkGIS** [comment]
This just happened again, after upgrading to the release version of `Visual Studio 2015`.

Same procedure as mentioned above by @cdglove 

* `%TEMP%` <- paste this into address bar of file explorer
* and delete
  * `b2_msvc_14.0_vcvarsall_x86.cmd`
  * `b2_msvc_14.0_vcvarsall_x86_amd64.cmd`
  * `b2_msvc_14.0_vcvarsall_x86_arm.cmd`

**Comment by zvanjak** [comment]
Saved my day! Thanks.
