### ISSUE TITLE
error running build_mapnik.bat: 'powershell' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#29]
![screen shot 2015-02-25 at 3 49 57 pm](https://cloud.githubusercontent.com/assets/20300/6383513/0efd3b32-bd06-11e4-95c7-a792b0c32903.png)

@BergWerkGIS - any ideas what I need to do to avoid the "powershell" not found error? this is on my aws machine I've been using for several months. I ran `settings.bat`, then `build_mapnik.bat`, then hit this.

**Comment by springmeyer** [comment]
looks like its `set PATH=C:\Windows\System32\WindowsPowershell\v1.0\;%PATH%`

**Comment by BergWerkGIS** [comment]
Strange. It should already be on %PATH% on recent OSes.
I suppose you are using 2012?

Did you change any Windows features?
While researching this, I found out, that PowerShell can suddenly disappear when doing so.

For later reference:

* check if `C:\Windows\System32\WindowsPowershell\v1.0` exists
  * if directory does not exist or is empty , enable Powershell: like so
```
dism.exe /online /enable-feature /featurename:MicrosoftWindowsPowerShellRoot
dism.exe /online /enable-feature /featurename:MicrosoftWindowsPowerShell /all
```
* check if Powershell is available via `where powershell`
  * if it's not available add its directory to PATH:  
```
set PATH=C:\Windows\System32\WindowsPowershell\v1.0;%PATH%
```

Reference:
http://serverfault.com/questions/431010/server-2012-server-core-powershell-not-installed

**Comment by springmeyer** [comment]
I'm now hitting broken/missing PATH to powershell on my AWS win ec2 when I run settings.bat. Going to add the path in there now to avoid having to re-find this ticket.

![screen shot 2015-03-19 at 11 30 31 am](https://cloud.githubusercontent.com/assets/20300/6737836/70eedda6-ce2b-11e4-9e28-b11f1605eb8a.png)
