### ISSUE TITLE
Fixed versions for everything

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/windows-builds#31]
@springmeyer 

__tl;dr__

I suggest, that we stick to fixed versions (S3:://mpanik/deps downloads) for everything we need for our builds.
Not just the sources, but also binary dependencies.

What do you think?

-----

I spent yesterday and today debugging why `cairo` suddenly stopped compiling on our new Windows build server with
```
sh: C:\Program: No such file or directory"
```

Strange thing: It compiles without problems on the instance I created the build server AMI from!
hrmm, _scratches head_ :question: :question: :question: 

I tried everything that came to my mind, e.g.
  * changed all env vars (mainly `%PATH%`) to use short (MSDOS style 8.3) paths (`C:\Program Files\` -> `C:\PROGRA~1`, `C:\Program Files (x86)\` -> `C:\PROGRA~2`)
  * verified that `sh.exe` was available on a short path, but nothing helped.
  * ...

More by chance than anything else I stumbled upon the download of `make.exe` which we got from
ftp.equation.com in [settings.bat](https://github.com/mapbox/windows-builds/blob/b8538afd96ffa367dd22b83bf9b8076b7ca0da65/settings.bat#L163).

It turns out, that they updated `make.exe` yesterday and the new version does not work for building cairo.
Luckily I hadn't deleted the `tmp-bin` on the test server.

In the meantime I've also found out that we were using version `3.82` and __`cairo` just compiles with this version__.
Neither `3.81`, `4.1` nor `4.2` work.

I've already put `make.exe@3.82` on S3.

**Comment by springmeyer** [comment]
caching deps (both build and package) sounds good. That way we can spend time debugging differences from upstream only when we are ready :)

**Comment by BergWerkGIS** [comment]
Done!
