### ISSUE TITLE
PolygonSymbolizer doesn't work

### ISSUE THREAD

**Issue by cboittin** [mapbox/windows-builds#32]
I installed the 64 bits build of mapnik given by @BergWerkGIS (thanks !) at https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-14.0-x64-v3.0.0-rc1-645-gfe01d52.7z following https://github.com/mapnik/mapnik-packaging/issues/188, and it seems to work with Python 2.7 64 bits (import works fine, at least).

However, when trying to run the example script (https://github.com/mapnik/mapnik/wiki/GettingStartedInPython), i get this error :

```
Traceback (most recent call last):
  File "mapnikTest.py", line 6, in <module>
    polygon_symbolizer = mapnik.PolygonSymbolizer(mapnik.Color('#f2eff9'))
Boost.Python.ArgumentError: Python argument types in
    PolygonSymbolizer.__init__(PolygonSymbolizer, Color)
did not match C++ signature:
    __init__(struct _object * __ptr64)
```

EDIT : Works in XML, so it's probably related to https://github.com/mapnik/mapnik-support/issues/22 ?

**Comment by BergWerkGIS** [comment]
@cboittin Yes, this is currently broken.

_"For now the recommendation is to only interface with Text labeling in Mapnik **through XML** and not via python bindings."_
https://github.com/mapnik/mapnik/issues/2225

**Comment by alexchamberlain** [comment]
Is this still the case? If so, is it worth adding that to  https://github.com/mapnik/mapnik/wiki/GettingStartedInPython?
