### ISSUE TITLE
Switch Windows builds of mapnik to using jpeg-turbo rather then standard jpeg library.

### ISSUE THREAD

**Issue by flippmoke** [mapbox/windows-builds#33]
@BergWerkGIS could you look into this?

**Comment by BergWerkGIS** [comment]
It this what's used on other platforms, too?

As far as I've looked into it, it seems to require additional dependencies, we don't yet have:

* [MSYS](http://www.mingw.org/wiki/msys)
* JDK 32bit
* JDK 64bit

At least I'm hitting a wall without those:


__Even, when building with Visual Studio the build process has to be started from the MYSYS shell.__
This seems difficult to be integrated in our current workflow.

See [docs about buildscripts](http://sourceforge.net/p/libjpeg-turbo/code/HEAD/tree/buildscripts/libjpeg-turbo/):
_The Windows native builds (both Visual C++ and MinGW) must be conducted from
within an MSYS shell._

And which one of those do we need?
I suppose, just `jpeg`.

![image](https://cloud.githubusercontent.com/assets/4549888/6801153/a5fc075a-d225-11e4-96a8-051f7f416e1c.png)

**Comment by springmeyer** [comment]
> It this what's used on other platforms, too?

Yes, this is what is used on osx + linux: https://github.com/mapnik/mapnik-packaging/blob/master/osx/scripts/build_jpeg_turbo.sh

> within an MSYS shell.

Bizarre. Right, we only need the libjpeg (I think the final binary should be named jpeg.dll) it produces. Can you find anyone else that has been able to build just the libjpeg? I wonder how Chromium does it: do they use jpeg-turbo or the original libjpeg?

**Comment by BergWerkGIS** [comment]
I just made it work this very moment.
Turns out, I needed to create make files with CMake and install `nasm`http://nasm.us/.

These are the binaries I get:

![image](https://cloud.githubusercontent.com/assets/4549888/6807097/cb8322fc-d24c-11e4-8b9a-d49960011ba5.png)

![image](https://cloud.githubusercontent.com/assets/4549888/6807099/cf589f60-d24c-11e4-9b80-ac1443efde1d.png)

**Comment by springmeyer** [comment]
@BergWerkGIS - are we officially using jpeg-turbo now or does this still need finished?

**Comment by BergWerkGIS** [comment]
@springmeyer no, still using libjpeg. I'll look into it.

**Comment by BergWerkGIS** [comment]
Done.
Lastest mapnik/master and node-mapnik/master compile successfully.
Leaving open and assigned to publish new packages.

**Comment by springmeyer** [comment]
:pray:

**Comment by BergWerkGIS** [comment]
AppVeyor for `node-mapnik` is green with new mapnik SDK.
https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.563

**Comment by springmeyer** [comment]
YAYYYYYY: I've removed the hacks disabling or reducing the comparison threshold for jpeg image fixtures. And after using a Win SDK with jpeg-turbo all tests are still passing: https://ci.appveyor.com/project/Mapbox/node-mapnik/build/1.0.575
