### ISSUE TITLE
Upgrade to GDAL 1.11.2

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#36]
Mapnik unix builds and node-gdal (https://github.com/naturalatlas/node-gdal/issues/90) are moving to gdal 1.11.2, so we should match that here. It looks like we are currently building gdal 1.11.1, but we should move to 1.11.2.

**Comment by BergWerkGIS** [comment]
done 
https://github.com/mapbox/windows-builds/commit/977a8b3ebeafebad6c8c21a0305c08fadde87ecb

**Comment by BergWerkGIS** [comment]
reopening:

still have to update the deps binary package for fast builds!

till then use commit flag `[nofastbuild]` got get a real 1.11.2 build.

**Comment by BergWerkGIS** [comment]
Updated binary package for dependencies is in place.
