### ISSUE TITLE
mapnik-sdk c++ runtime

### ISSUE THREAD

**Issue by jbrwn** [mapbox/windows-builds#38]
Is there a published mapnik-sdk package available that is built on the VS2015 CTP6 c++ runtime?   Thanks in advance!

**Comment by jskulavik** [comment]
Actually the runtime that would be preferable would be the Microsoft Visual C++ 2015 RC - 14.0.22816 rather than the CTP6 version

**Comment by springmeyer** [comment]
Hey there @jbrwn and @jskulavik. I just walk talking with @BergWerkGIS about this last week. He is working on it and I think its pretty close, but not yet available. He is on vacation this week so it would be great if you could ping here again next week.

**Comment by jskulavik** [comment]
Will do, thank you very much @springmeyer!

**Comment by BergWerkGIS** [comment]
@jbrwn @jskulavik 
I was able to build mapnik with VS2015 CTP6, but haven't published a package as I had some quirks with it on my dev machine.
Will try with [RC](https://www.visualstudio.com/en-us/news/vs2015-vs.aspx) during the next days.

**Comment by jbrwn** [comment]
Thanks @BergWerkGIS !

**Comment by BergWerkGIS** [comment]
Progess report:
Tried with VS2015 RC Enterprise Edition: all dependencies seem to compile fine, but I get ~60 errors with mapnik.
Most of them pointing either to icu or tiff.
Will investigate further.

**Comment by jskulavik** [comment]
Thank you so very much @BergWerkGIS

**Comment by BergWerkGIS** [comment]
@jbrwn @jskulavik 

The first SDK built with VS2015 RC 14.0.22816.
Please use at own risk :smirk: 
 
x64:
https://mapnik.s3.amazonaws.com/dist/dev/vs2015rc1/mapnik-win-sdk-14.0-x64-v3.0.0-rc1-1126-g340ed85.7z

x86:
https://mapnik.s3.amazonaws.com/dist/dev/vs2015rc1/mapnik-win-sdk-14.0-x86-v3.0.0-rc1-1126-g340ed85.7z

**Comment by jbrwn** [comment]
@BergWerkGIS you the man :+1:

**Comment by BergWerkGIS** [comment]
@jbrwn thanks, but wouldn't have been possible without @springmeyer 's help.

**Comment by jskulavik** [comment]
Yes, thank you very much @BergWerkGIS & @springmeyer.  I'll give it a go and see what happens

**Comment by BergWerkGIS** [comment]
@jbrwn @jskulavik 

I've created a test SDK with the VS2015 release version:

x64:
https://mapnik.s3.amazonaws.com/dist/dev/vs2015/mapnik-win-sdk-14.0-x64-v3.0.0-32-g25af931.7z

x86:
https://mapnik.s3.amazonaws.com/dist/dev/vs2015/mapnik-win-sdk-14.0-x86-v3.0.0-32-g25af931.7z

Let me know, if this works for you?

**Comment by BergWerkGIS** [comment]
Oh, I forgot: it is a **`Release`** build, but includes debug symbols (`PDBs`).
That's why the package is bigger.

Is this useful for you, or would you prefer to have two packages availble for each bitness?
One with, and one without PDBs?

**Comment by jskulavik** [comment]
I'll get going on this tonight.  Thanks @BergWerkGIS!  I'd say one package is fine.

**Comment by BergWerkGIS** [comment]
Updated VS2015 mapnik SDK:

x64:
https://mapnik.s3.amazonaws.com/dist/dev/vs2015/mapnik-win-sdk-14.0-x64-v3.0.1-4-ga78a895.7z

x86:
https://mapnik.s3.amazonaws.com/dist/dev/vs2015/mapnik-win-sdk-14.0-x86-v3.0.1-4-ga78a895.7z

**Comment by BergWerkGIS** [comment]
Updated VS2015 mapnik SDK:

x64:
https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-v3.0.3-x64-14.0.7z

x86:
https://mapnik.s3.amazonaws.com/dist/dev/mapnik-win-sdk-v3.0.3-x86-14.0.7z

**Comment by jskulavik** [comment]
Thanks @BergWerkGIS!  I'm planning on adding this to a new project that I'm going to get off of the ground [here](http://github.com/jskulavik/meristem)

**Comment by BergWerkGIS** [comment]
@jskulavik wow, the ReadME sounds promising.
