### ISSUE TITLE
VS 2015 RC Protoc.exe 

### ISSUE THREAD

**Issue by jbrwn** [mapbox/windows-builds#39]
@BergWerkGIS - I'm getting some weird errors when trying to use the protoc.exe that is bundled with the mapnik-sdk here:

x64:
https://mapnik.s3.amazonaws.com/dist/dev/vs2015rc1/mapnik-win-sdk-14.0-x64-v3.0.0-rc1-1126-g340ed85.7z

x86:
https://mapnik.s3.amazonaws.com/dist/dev/vs2015rc1/mapnik-win-sdk-14.0-x86-v3.0.0-rc1-1126-g340ed85.7z

Everything worked fine locally on a fresh windows server 2008 r2 machine with VS 2015 RC installed.   However, the executable starting throwing errors in appveyor images (see screenshot below).  I get the error on both Visual Studio 2015 CTP 6 and Visual Studio 2015 RC build workers.  [Here is the issue i opened up at appveyor for this](http://help.appveyor.com/discussions/problems/2124-command-fails-with-error-code-255-on-visual-studio-2015-rc-image).

Can you confirm the version of visual studio 2015/C runtime was used to compile the protoc.exe that is bundled with mapnik-sdk?  I'm thinking there might be some weird C runtime issues going on.  

![image](https://cloud.githubusercontent.com/assets/1198377/7613356/75c8fb8e-f94d-11e4-93f3-df4e4de71b84.png)

**Comment by BergWerkGIS** [comment]
@jbrwn 
Y, I did a clean rebuild, so everything should be RC.
would you mind posting a bigger screenshot?

**Comment by jbrwn** [comment]
Ha.  Sorry about potato quality.  This should be better:

![image](https://cloud.githubusercontent.com/assets/1198377/7613909/d0e861f0-f950-11e4-8b38-c97e7473aa47.png)

**Comment by BergWerkGIS** [comment]
hrm, yes, that looks like a conflict between wrong runtimes.
I'm about to power down now, but will verify later in the evening or tomorrow.

**Comment by jbrwn** [comment]
Thanks @BergWerkGIS

**Comment by BergWerkGIS** [comment]
@jbrwn 
I've verified, that it works for me on AppVeyor via RDP.

It seems you are using the wrong SDK in your [AppVeyor.yml#L20](https://github.com/jbrwn/NET-Mapnik/blob/vs2015-rc/appveyor.yml#L20):
<pre>
(New-Object Net.WebClient).DownloadFile("http://mapnik.s3.amazonaws.com/<b>dist/dev/</b>mapnik-win-sdk-14.0-$env:Platform-v3.0.0-rc1-1126-g340ed85.7z", "$pwd\mapnik-win-sdk.7z")
</pre>
which should be:
<pre>
https://mapnik.s3.amazonaws.com/<b>dist/dev/vs2015rc1/</b>mapnik-win-sdk-14.0-x64-v3.0.0-rc1-1126-g340ed85.7z
</pre>

**Comment by jbrwn** [comment]
oh. my. god.  I went through like 30 builds on appveyor trying to figure out what was going on.  

thanks for saving me from myself @BergWerkGIS.

**Comment by BergWerkGIS** [comment]
:smile:
