### ISSUE TITLE
[settings.bat] curl: certificate problem, unable to get local issuer certificate

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/windows-builds#41]
refs https://github.com/mapnik/mapnik/issues/2811#issuecomment-106162315

----

@camviluong 

Please check if you already have a `tmp-bin` directory in your clone directory.
If yes, delete it.

Then do a `git pull` and try again.
Does it work?

**Comment by camviluong** [comment]
hi @BergWerkGIS ,

I have check it, a tmp-bin directory is not exists. I have delete all of windows-builds folder and run clone againt. It work! 

I am building packages now. Thanks

**Comment by BergWerkGIS** [comment]
Perfect!
