### ISSUE TITLE
Visual Studio 14 Win64 vs Visual Studio 14 2015 Win64

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#44]
I noticed that `stxxl` uses `Visual Studio 14 2015 Win64` while other cmake builds us `Visual Studio 14 Win64`. Is there any functional difference or are these the same?

**Comment by BergWerkGIS** [comment]
No, as the internal version of `VS2014` and `VS2015` is `14`.
`Visual Studio 14 2015 Win64` is just more verbose.
