### ISSUE TITLE
node-gdal v0.5.0 32 bit binaries

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#46]
The latest node-gdal release is missing 32 bit binaries for the `--toolset=v140` builds targeting Visual Studio 2014. Based on https://github.com/mapbox/windows-builds/commit/5d321357f24b4ab87c24f600e5e4ef8e2306423f it looks like @BergWerkGIS knows this :) Just creating this ticket to track the issue. Sorry if I missed a different ticket and this is a dupe.

**Comment by BergWerkGIS** [comment]
oh, I missed publishing 32 bit.
Done now!
