### ISSUE TITLE
Target Visual Studio 2015 (drop 2014 CTP)

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#49]
Once http://blogs.windows.com/buildingapps/2015/06/29/release-dates-and-compatibility-visual-studio-2015-and-windows-10-sdk/ drops let's move to 2015 and never look back.

Once done:

 - [ ] Add binary download links to mapnik.org page: https://github.com/mapnik/mapnik.github.com/blob/master/pages/downloads.md#prebuilt-binaries
 - [ ] Studio Release
 - [ ] Email to mapnik users list

Refs https://github.com/mapbox/mapbox-studio/issues/1404

**Comment by BergWerkGIS** [comment]
mapnik 3.0.2 Windows binaries are available here:

https://mapnik.s3.amazonaws.com/dist/v3.0.2/mapnik-win-sdk-v3.0.2-x64-14.0.7z
https://mapnik.s3.amazonaws.com/dist/v3.0.2/mapnik-win-sdk-v3.0.2-x86-14.0.7z

@flippmoke 
How would I update the mapnik.org page?
Just edit the `downloads.md`?

**Comment by alex85k** [comment]
By the way, Boost 1.59 fully supports VS 2015 (no more warnings).

**Comment by springmeyer** [comment]
we have been on vs 2015 for several months now, closing.
