### ISSUE TITLE
Update freetype and harfbuzz, drop libxml

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/windows-builds#54]
freetype -> 2.6
harfbuzz -> 0.9.41
to be in sync with
https://github.com/mapnik/node-mapnik/blob/master/CHANGELOG.md#341

**Comment by BergWerkGIS** [comment]
drop libxml
https://github.com/mapnik/mapnik-packaging/commit/134bc9bfc574ca300934019f96266978dff803ba

**Comment by BergWerkGIS** [comment]
compare to other deps versions, too:
https://github.com/mapnik/mapnik-packaging/blob/master/osx/settings.sh#L414-L492

**Comment by BergWerkGIS** [comment]
Update done:

* freetype
* harfbuzz
* icu
* boost
* libpng
* libtiff
* sqlite

Also uploaded new binary deps packages for `FASTBUILD=1`.

**Still TODO: drop libxml.**

**Comment by springmeyer** [comment]
libxml2 drop happened in https://github.com/mapbox/windows-builds/commit/a59a9c1f62e4d66babafbdfc75c811b57eb30580, closing.
