### ISSUE TITLE
Update to boost 1.59

### ISSUE THREAD

**Issue by BergWerkGIS** [mapbox/windows-builds#56]
https://github.com/mapbox/windows-builds/issues/49#issuecomment-133038882

**Comment by BergWerkGIS** [comment]
First build with `1.59` was successful without any changes.
Will test `mapnik`/`node-mapnik` and then make `1.59` default.

**Comment by springmeyer** [comment]
let's keep Mapnik-packaging in sync. can you ask @Flippmoke for help to know how to update it as well?

**Comment by BergWerkGIS** [comment]
@springmeyer sure, still testing, as @artemp mentioned some problems with `boost@1.59` on *nix.
See also: https://github.com/mapnik/mapnik/issues/3065

**Comment by springmeyer** [comment]
Over here now: #62
