### ISSUE TITLE
x64 debug build does not work at all.

### ISSUE THREAD

**Issue by joycepg** [mapbox/windows-builds#58]
multiple issues. to reproduce, run
`settings.bat "BUILD_TYPE=Debug" "SKIP_FAILED_PATCH=true" "FASTBUILD=0"`
`scripts\build`
I had to add the skip failed patches to even get started.

- zlib build failed on the masm step. I had to download a pull request off zlib github site for vc14.
- libpng build failed. i had to run `path C:\Users\Paul\Documents\windows-builds\packages\zlib;%path%` before running build.bat so libpng build would find zlib.dll
- i have sent a pull request for a fix to build_freetype.bat
- the .sln for expat has win32 references all through the x64 target, eg, it builds to ..\win32\bin\Debug\libexpat.dll. here is the warning from the build
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(1189,5): warning MSB8012: TargetPath(C:\Users\Paul\Documents\windows-builds\packages\expat\lib\.\..\ **x64**\bin\Debug\expat.dll) does not match the Linker's OutputFile property value (C:\Users\Paul\Documents\windows-builds\packages\expat\ **win32**\bin\Debug\libexpat.dll).
- gdal build fails, looking for **win32** **Release** version of libexpat. double fail! here is the link command:
        link /nologo /dll /INCLUDE:OGRFeatureStylePuller  /INCLUDE:OSRValidate  /INCLUDE:OPTGetProjectionMethods  /INCLUDE:OGR_G_GetPointCount  /INCLUDE:OGRRegisterAll /INCLUDE:GDALSimpleImageWarp  /INCLUDE:GDALReprojectImage  /INCLUDE:GDALComputeMedianCutPCT  /INCLUDE:GDALDitherRGB2PCT  /INCLUDE:OCTNewCoordinateTransformation port\*.obj gcore\*.obj alg\*.obj frmts\o\*.obj ogr\ogrsf_frmts\ogrsf_frmts.lib ogr\ogr.lib   legacy_stdio_definitions.lib   "C:\Users\Paul\Documents\windows-builds\packages\expat"\win32\bin\Release\libexpat.lib               "C:\Users\Paul\Documents\windows-builds\packages\libtiff\libtiff\libtiff_i.lib"  C:\Users\Paul\Documents\windows-builds\packages\sqlite\sqlite3.lib                odbc32.lib odbccp32.lib user32.lib                     ws2_32.lib gcore\Version.res  /out:gdal200.dll /implib:gdal_i.lib   /debug
LINK : fatal error LNK1104: cannot open file 'C:\Users\Paul\Documents\windows-builds\packages\expat\win32\bin\Release\libexpat.lib'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.EXE"' : return code '0x450'

**Comment by BergWerkGIS** [comment]
@joycepg `Debug` builds are not maintained anymore (haven't cleaned up the scripts yet).

We've switched to **"`Release` with debug symbols"**, as keeping up with the combinations of Debug/Release * x86/x64 * VS2013/VS2015 became too much of a hassle.

FYI:
VS2013 support is also going to be dropped soon, as the tools (mapnik, node-mapnik, osrm, libosmium, ...) we build these dependencies for, use C++11 which isn't supported by VS2013.

**Comment by joycepg** [comment]
ok, yes windows builds are way too complicated in general (static/dll, runtime static/dll, debug/release, x86/x64).
fyi, i did get the x86 debug build to work ok. you have a pull request with the few minor changes if you want.

**Comment by BergWerkGIS** [comment]
I'd rather not accept the pull request now, as I'm lacking bandwidth to support it properly.

However, I've created a ticket with ideas for further improvements.

Feel free to add anything you consider useful to add in future iterations:
https://github.com/mapbox/windows-builds/issues/59
