### ISSUE TITLE
Boost 1.59

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#62]
Currently seeing:

```
LINK : fatal error LNK1104: cannot open file 'libboost_filesystem-vc140-mt-1_59.lib' [Z:\mb\windows-builds-64\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
```

**Comment by springmeyer** [comment]
hoping https://github.com/mapbox/windows-builds/commit/130f040ca357e6893c649b4be7a4650efd7acec7 will magically fix this...

**Comment by springmeyer** [comment]
yes, that fixed it.

**Comment by BergWerkGIS** [comment]
Depending on which build script you are using, `BOOST_VERSION` has to be set:

[mapnik::build-local.bat](https://github.com/mapnik/mapnik/blob/master/scripts/build-local.bat#L13)
[mapnik::appveyor.yml](https://github.com/mapnik/mapnik/blob/master/appveyor.yml#L3)

[windows-builds::settings.bat](https://github.com/mapbox/windows-builds/blob/master/settings.bat#L27)
