### ISSUE TITLE
could not create BreakIterator: U_MISSING_RESOURCE_ERROR

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#63]
@BergWerkGIS this is happening when running the visual tests in `windows-builds`. This error indicates the ICU_DATA path is not pointing to the `.dat` file. Or potentially that there is a mismatch in versions: e.g. we are using icu 55 with a .dat file from 54. However I can't see anything wrong with the scripts. Maybe you have ideas?

/cc @flippmoke

**Comment by springmeyer** [comment]
Looks like the problem might be that the data libraries are downloaded [here](https://github.com/mapnik/mapnik-gyp/blob/master/build.bat#L677-L680), but that happens after the tests are run and needs to happen before?

**Comment by BergWerkGIS** [comment]
fixed https://github.com/mapnik/mapnik-gyp/commit/ee8489048874f9a09daa040f85cc021490559daa
