### ISSUE TITLE
[Feature request]Optional libxml2 support?

### ISSUE THREAD

**Issue by jc101** [mapbox/windows-builds#66]
Would it break anything if including libxml2 support was optional? I see that it was included but was recently removed. I'm trying to use entities in xml styling files but they don't work which I've read [here](http://forum.openstreetmap.org/viewtopic.php?id=32231) is due to libxml2 support being required.

**Comment by springmeyer** [comment]
A vastly simplier solution would be just to run the style through `xmllint --noent` first to handle the entities. And then read the resulting XML with Mapnik - then Mapnik will not need support for libxml2.

**Comment by jc101** [comment]
Thanks, you're right - I didn't know xmllint could do that!
