### ISSUE TITLE
Upgrade deps

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#68]
Need to match https://github.com/mapnik/mapnik-packaging/pull/197 as well as icu upgrade mentioned in  #67

**Comment by BergWerkGIS** [comment]
Stuck at `harfbuzz` at the moment:

```
c:\mb\windows-builds-64\packages\harfbuzz\src\hb-buffer-private.hh(51): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\mb\windows-builds-64\packages\harfbuzz\src\hb-buffer-private.hh(52): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
c:\mb\windows-builds-64\packages\harfbuzz\src\hb-buffer-private.hh(67): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
```

**Comment by springmeyer** [comment]
Looks like this change may have broken compilation with vs 2015: https://github.com/behdad/harfbuzz/commit/167c3271778cd1a8c4433b9d2230901ce17c099e#diff-69538b0bfd6ad743ba41ec2f883af18f /cc @fanc999

**Comment by springmeyer** [comment]
hoping that https://github.com/behdad/harfbuzz/commit/f94c0ecbb1488138d3ec3b9d6d9fb78113dfee4f (and therefore upgrading to 1.1.1) will solve the compile error.

**Comment by BergWerkGIS** [comment]
Upgrading to `harfbuzz@1.1.1` and changing at bit of the CMake file solved the compile.

Although getting some test crashes:
```
Assertion in file gdaldrivermanager.cpp, line 415
```

Hope this gets merged into master soon:
`Enable Build of HarfBuzz under Visual Studio using NMake Makefiles`: https://github.com/behdad/harfbuzz/pull/164/files

**Comment by BergWerkGIS** [comment]
Merged https://github.com/mapbox/windows-builds/pull/69
