### ISSUE TITLE
Harfbuzz built with `-HB_NO_MT`

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#70]
It looks like harfbuzz is being built with `-HB_NO_MT`. Let's plan to strip this from the cmake file we use as per https://github.com/behdad/harfbuzz/issues/190

/cc @BergWerkGIS

**Comment by springmeyer** [comment]
@BergWerkGIS - could you prioritize this? It should be an easy fix (I presume). Basically `-HB_NO_MT` I think is being set in the cmake file we download dynamically and it needs to be removed.

**Comment by BergWerkGIS** [comment]
Done https://github.com/mapbox/windows-builds/commit/a565fc97d937e1dd0aa9a7dc76be2cca3a8d47aa

Updated the binary deps packages (for `FASTBUILD=1`) too:

* x86 https://mapbox.s3.amazonaws.com/windows-builds/windows-build-deps/mapnik-win-sdk-binary-deps-14.0-x86.7z
* x64 https://mapbox.s3.amazonaws.com/windows-builds/windows-build-deps/mapnik-win-sdk-binary-deps-14.0-x64.7z

----

Came across a new `libpng` build error on the way, but appears only with `x64`, **not** `x86`.
Tracking here https://github.com/mapbox/windows-builds/issues/71

**Comment by springmeyer** [comment]
@BergWerkGIS thank you. Can https://github.com/mapnik/node-mapnik/issues/568 be closed now? See also https://github.com/mapnik/node-mapnik/issues/578 which will require another SDK update after https://github.com/mapbox/windows-builds/commit/63022b0a26ba3e2f5e88ea45009ac2a8ada2fc50

**Comment by BergWerkGIS** [comment]
> Can mapnik/node-mapnik#568 be closed now?

:+1: 

> See also mapnik/node-mapnik#578 which will require another SDK update after 63022b0

working on it.
