### ISSUE TITLE
Upgrade to gdal 2.0.2

### ISSUE THREAD

**Issue by springmeyer** [mapbox/windows-builds#84]
Currently at 2.0.1: https://github.com/mapbox/windows-builds/blob/master/settings.bat#L51

refs https://github.com/naturalatlas/node-gdal/issues/157 and https://github.com/mapnik/mapnik-packaging/commit/2cb431a5ce42088abe68d1c3632753e2f503e9d7

/cc @BergWerkGIS

**Comment by BergWerkGIS** [comment]
Seems to build ok, but visual test binaries crash:

![image](https://cloud.githubusercontent.com/assets/4549888/14328984/4b11820e-fc07-11e5-86e5-5a67e948da61.png)

Same for `test_rendering.exe`.

**Comment by BergWerkGIS** [comment]
Fixed above error by pinning harfbuzz CMakeLists.txt https://github.com/mapbox/windows-builds/commit/dc251f8087ec72af32972612fc796bfcab70c8b4#diff-02212129a2acdb0380f3820eed04254dR34

**Comment by BergWerkGIS** [comment]
New binary deps packages for `"FASTBUILD=1"` uploaded.

**Comment by springmeyer** [comment]
thanks @BergWerkGIS!
