### ISSUE TITLE
How to use this windows builds

### ISSUE THREAD

**Issue by hoogw** [mapbox/windows-builds#85]
I am new, don't know how to install it. 
I can't find any guide on How to use this windows builds.

Can you take  10 minutes write out the step by step will SAVE me a few days headache.

I think I am not alone.

**Comment by springmeyer** [comment]
@hoogw why are you interested in theses scripts? Generally there are not designed for public use.

**Comment by hoogw** [comment]
springmeyer,   I am try to install PGRestAPI on windows. However, without node-mapnik, PGRestAPI will NOT run. It complain can't find module mapnik.   

So I spend a week try to install mapnik for windows(success),

Then I try to install node-mapnik for windows, failed.  I did

 npm install mapnik@3.x

error out

the installation guide says windows builds bring me here.

I confused. What is correct way to install node-mapnik for PGRestAPI?

Thanks

**Comment by springmeyer** [comment]
node-mapnik provides binaries so you do not need, nor should you, have to source compile. Please create an issue at https://github.com/mapnik/node-mapnik/issues with the error message and we can help you figure out the problem. It is likely a missing vcredist, see https://github.com/mapnik/node-mapnik/#windows-specific

**Comment by hoogw** [comment]
springmeyer,  thank you.
after 1 week try and fail,  the node-mapnik issue resolve by some tips I want to share with other if they run into same problem.  

You MUST installed as default directory( if you choose other install directory could fail )

I am on 64bit operating system (W7, 8, 8.1, Server 2012)

1) Visual Studio 2015, earlier versions, is NOT ok, https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx (direct download)

2) Python 2.7 32 bit installed into C:\Python27 (MUST be this directory, MUST be 32 bit) other directory or 64 bit could fail you.

3) git installed into C:\Program Files (x86)\Git (MUST be this directory, Must be 32 bit)
Install Node.js MUST be 32 bit, into C:\Program Files (x86)\nodejs\ must be this directory.
Otherwise, could error, not sure why

4) install mapnik for windows, Verify the success by run demo python script to generate a bunch of image file as says in guide. (Must verify the success)

Now node-mapnik module should install automatically success.
