### ISSUE TITLE
get-scriptcs.ps1

### ISSUE THREAD

**Issue by hcfang2000** [mapbox/windows-builds#98]
settings.bat failed due to get-scriptcs.ps1?  How to solve it??  Thansk.

c:\dev2015\windows-builds>settings.bat
------------ checking for Powershell ------------
Powershell version:
Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1
Powershell execution policy: Unrestricted
Powershell execution policy now is: Unrestricted
Latest scripcs version: 0.16.1
URL: http://chocolatey.org/api/v2/package/ScriptCs/0.16.1
cwd: C:\dev2015\windows-builds
Cannot find an overload for "Combine" and the argument count: "3".
At C:\dev2015\windows-builds\scripts\get-scriptcs.ps1:35 char:37
+ $dl_file = [System.IO.Path]::Combine <<<< ($cwd, 'packages', 'scriptcs.zip')
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

!!!!!!!! ===== ERROR ==== !!!!!!!!
builds cannot be run unless settings.bat finished successfully

**Comment by BergWerkGIS** [comment]
@hcfang2000 seems you have PowerShell version `2.0` which is quite old (released 2009).
Could you update PowerShell and try again?

**Comment by hcfang2000** [comment]
Problem solved after installing Windows Management Framework 4.0.  Thanks.

**Comment by hcfang2000** [comment]
Problem solved after installing Windows Management Framework 4.0. Thanks.

**Comment by hcfang2000** [comment]
Problem solved after installing Windows Management Framework 4.0. Thanks.
